name: CI/CD

on: 
  push:
    branches:
      - master
    paths-ignore:
      - 'README.md'

jobs:

  build: 
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.1.7

    - name: Setting Up Go 1.22
      uses: actions/setup-go@v2
      with: 
        go-version: 1.22

    - name: Build 
      run: go build -o go-app

    - name: Test
      run: go test ./


  Code-Quality:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Run golang-lint
      uses: golangci/golangci-lint-action@v6
      with:
        version: v1.56.2
  Docker-Image-Push: 
    runs-on: ubuntu-latest

    needs: build

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3.5.0

    - name: Login to Dockerhub
      uses: docker/login-action@v3.3.0
      with: 
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v6.5.0
      with:
        path: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/go-port:${{github.run_id}}

  Updating-helm-tags:

      runs-on: ubuntu-latest
      steps:
      
      - name: Cloning the helm repo
        uses: whyakari/github-repo-action@v3.1
        with:
          owner: AmanPathak-DevOps
          repository: go-app-devops
          access-token: ${{ secrets.REPO-PAT }}
          branch: master


      - name: Updating values in helm
        run: |
          pwd
      
        
    
    
      
