name: CI/CD

on: 
  push:
    branches:
      - master
    paths-ignore:
      - 'README.md'

jobs:

  build: 
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.1.7

    - name: Setting Up Go 1.22
      uses: actions/setup-go@v2
      with: 
        go-version: 1.22

    - name: Build 
      run: go build -o go-app

    - name: Test
      run: go test ./


  Code-Quality:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Run golang-lint
      uses: golangci/golangci-lint-action@v6
      with:
        version: v1.56.2
  Docker-Image-Push: 
    runs-on: ubuntu-latest

    needs: build

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3.5.0

    - name: Login to Dockerhub
      uses: docker/login-action@v3
      with: 
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v6.5.0
      with:
        path: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/go-port:${{github.run_id}}

  Image-Scanning:
      runs-on: ubuntu-latest
      steps:

      - name: Running Vulnerability Check on Docker Image
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: 'docker.io/${{ secrets.DOCKER_USERNAME }}/go-port:${{ github.run_id }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: false
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

  Updating-helm-tags:

      runs-on: ubuntu-latest
      steps:
      
      - name: Cloning the helm repo
        uses: GuillaumeFalourd/clone-github-repo-action@v2.3
        with:
          owner: 'AmanPathak-DevOps'
          # repository: 'go-app-devops'
          repository: 'go-app-devops'
          access-token: ${{ secrets.REPO_PAT }}
          branch: 'master'


      - name: Updating values in helm
        run: |
          cd go-app-devops
          ls
          sed -i 's/tag: .*/tag: "${{github.run_id}}"/' values.yaml

      - name: Pushing changes
        run: |
          cd go-app-devops
          git config --global user.email "aman07pathak@gmail.com"
          git config --global user.name "AmanPathak-DevOps"
          git add values.yaml
          git commit -am "Updated values.yaml file"
          git push
      
        
    
    
      
